### ISSUE TITLE
Build and runtime dependencies

### ISSUE THREAD

**Issue by gokhanettin** [yunusem/pardus-store#3]
I manged to build the project but cannot run it. Can you write a detailed command line build steps for the project on `README.md` including QT_SELECT stuff?

- Which debian packages we need to build and run?
- What is the minimum Qt version?

My distro is Pardus 17.2 and here is the runtime error I am getting:
I tried installing all the qtdeclarative5* and qtquickcontrols* packages with no luck.
```
$ cd path/to/pardus-store
$ mkdir build
$ qmake ..
$ make
$ ./ps
QQmlApplicationEngine failed to load component
qrc:/ui/main.qml:2 module "QtQuick.Controls" version 2.0 is not installed
```

**Comment by yunusem** [comment]
yes it has some qml module runtime dependencies, since the application is not mature enough those runtime dependencies are changing commit to commit. My suggestion on this issue is that, try to install qml modules error specific like this :

`qrc:/ui/main.qml:2 module "QtQuick.Controls" version 2.0 is not installed`
`sudo apt install qml-module-qtquick-controls`

**Comment by gokhanettin** [comment]
Build and run dependencies are given in `debian/control` #14 gives link to prerequistes in README.md. When it is merged, we can close this.

**Comment by gokhanettin** [comment]
`debian/control` file contains all the build and run-time dependencies.
